# Generated by Django 3.1.6 on 2021-06-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('motdepass', models.CharField(max_length=8)),
                ('localisation', models.CharField(max_length=50)),
                ('gps', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reflecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumFiber', models.CharField(max_length=5)),
                ('PerteConnecteur', models.CharField(max_length=50)),
                ('CumuleConnecteur', models.CharField(max_length=50)),
                ('PerteDistance', models.CharField(max_length=50)),
                ('CumuleDistance', models.CharField(max_length=50)),
                ('BilanPertes', models.CharField(max_length=50)),
                ('LongueurCable', models.CharField(max_length=50)),
                ('Episure', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descrp', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tchat.category')),
            ],
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('lat', models.CharField(default=0, max_length=200)),
                ('lng', models.CharField(default=0, max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tchat.zone')),
            ],
        ),
    ]
