# Generated by Django 3.1.6 on 2021-06-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tchat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresse',
            name='adresse',
        ),
    ]
