# Generated by Django 3.1.6 on 2021-06-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tchat', '0002_remove_adresse_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflecto',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
