# Generated by Django 3.1.6 on 2021-06-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tchat', '0003_reflecto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reflecto',
            name='image',
        ),
    ]
