# Generated by Django 3.1.6 on 2021-06-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tchat', '0004_remove_reflecto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflecto',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
