# Generated by Django 3.1.6 on 2021-06-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tchat', '0005_reflecto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reflecto',
            old_name='image',
            new_name='lala',
        ),
    ]
