# Generated by Django 3.1.6 on 2021-06-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tchat', '0006_auto_20210619_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reflecto',
            old_name='lala',
            new_name='photo',
        ),
    ]
