# Generated by Django 3.1.6 on 2021-07-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tchat', '0007_auto_20210619_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumFiber', models.CharField(max_length=5)),
                ('PerteConnecteur', models.CharField(max_length=50)),
                ('CumuleConnecteur', models.CharField(max_length=50)),
                ('PerteDistance', models.CharField(max_length=50)),
                ('CumuleDistance', models.CharField(max_length=50)),
                ('BilanPertes', models.CharField(max_length=50)),
                ('LongueurCable', models.CharField(max_length=50)),
                ('Episure', models.CharField(max_length=50)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
