# Generated by Django 3.1.6 on 2021-07-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tchat', '0008_mesurer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesurer',
            name='photo',
        ),
    ]
