# Generated by Django 3.1.6 on 2021-07-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tchat', '0009_remove_mesurer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesurer',
            name='rapport',
            field=models.FileField(blank=True, upload_to='static/rapport'),
        ),
    ]
