# Generated by Django 3.1.6 on 2021-07-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tchat', '0011_auto_20210715_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesurer',
            name='rapport',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
